### PR TITLE
Add hero section

### PR DESCRIPTION
**Pull request by Azizbek-personal**
Made a hero section

### CODE REVIEW

**Comment by Byte-Synergy** [comment]
You have a problem with left side, where included texts. there are gaps are big, you don't have a height on rightside

**Comment by Azizbek-personal** [comment]
> You have a problem with left side, where included texts. there are gaps are big, you don't have a height on rightside

there are big gaps only in tablet sizes, i want you to remember that yet we don't have a responsivity of this section

Thank you, 
Developer

**Comment by Byte-Synergy** [comment]
> there are big gaps only in tablet sizes, i want you to remember that yet we don't have a responsivity of this sect...

ok i have checked it, everything works good

**Review by Byte-Synergy — COMMENTED** [review]
Ok let's check it on dev mode

**Pull request merged**
